from __future__ import annotations

import re

SPAIN_LOCATION_TERMS = (
    "spain",
    "españa",
    "espana",
    "galicia",
    "madrid",
    "barcelona",
    "valencia",
    "andalusia",
    "andalucía",
    "andalucia",
    "a coruña",
    "coruña",
    "vigo",
    "pontevedra",
    "málaga",
    "malaga",
)

BROAD_SPAIN_COMPATIBLE_TERMS = (
    "worldwide",
    "global",
    "anywhere",
    "international",
    "european union",
    "europe",
    "emea",
    "eu remote",
)

# Country names and common hiring-location aliases.
#
# Spain is intentionally excluded because it has its own positive scope.
# Two-letter ISO codes are intentionally NOT used generally because many
# collide with ordinary words, US state abbreviations, or city names.
FOREIGN_COUNTRY_TERMS = (
    "afghanistan",
    "albania",
    "algeria",
    "andorra",
    "angola",
    "antigua and barbuda",
    "argentina",
    "armenia",
    "australia",
    "austria",
    "azerbaijan",
    "bahamas",
    "bahrain",
    "bangladesh",
    "barbados",
    "belarus",
    "belgium",
    "belize",
    "benin",
    "bhutan",
    "bolivia",
    "bosnia and herzegovina",
    "bosnia",
    "botswana",
    "brazil",
    "brunei",
    "bulgaria",
    "burkina faso",
    "burundi",
    "cabo verde",
    "cape verde",
    "cambodia",
    "cameroon",
    "canada",
    "central african republic",
    "chad",
    "chile",
    "china",
    "colombia",
    "comoros",
    "congo",
    "democratic republic of the congo",
    "costa rica",
    "côte d'ivoire",
    "cote d'ivoire",
    "ivory coast",
    "croatia",
    "cuba",
    "cyprus",
    "czechia",
    "czech republic",
    "denmark",
    "djibouti",
    "dominica",
    "dominican republic",
    "ecuador",
    "egypt",
    "el salvador",
    "equatorial guinea",
    "eritrea",
    "estonia",
    "eswatini",
    "swaziland",
    "ethiopia",
    "fiji",
    "finland",
    "france",
    "gabon",
    "gambia",
    "georgia",
    "germany",
    "ghana",
    "greece",
    "grenada",
    "guatemala",
    "guinea",
    "guinea-bissau",
    "guyana",
    "haiti",
    "honduras",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "israel",
    "italy",
    "jamaica",
    "japan",
    "jordan",
    "kazakhstan",
    "kenya",
    "kiribati",
    "north korea",
    "south korea",
    "korea",
    "kuwait",
    "kyrgyzstan",
    "laos",
    "latvia",
    "lebanon",
    "lesotho",
    "liberia",
    "libya",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "madagascar",
    "malawi",
    "malaysia",
    "maldives",
    "mali",
    "malta",
    "marshall islands",
    "mauritania",
    "mauritius",
    "mexico",
    "micronesia",
    "moldova",
    "monaco",
    "mongolia",
    "montenegro",
    "morocco",
    "mozambique",
    "myanmar",
    "burma",
    "namibia",
    "nauru",
    "nepal",
    "netherlands",
    "holland",
    "new zealand",
    "nicaragua",
    "niger",
    "nigeria",
    "north macedonia",
    "macedonia",
    "norway",
    "oman",
    "pakistan",
    "palau",
    "panama",
    "papua new guinea",
    "paraguay",
    "peru",
    "philippines",
    "poland",
    "portugal",
    "qatar",
    "romania",
    "russia",
    "russian federation",
    "rwanda",
    "saint kitts and nevis",
    "saint lucia",
    "saint vincent and the grenadines",
    "samoa",
    "san marino",
    "sao tome and principe",
    "saudi arabia",
    "senegal",
    "serbia",
    "seychelles",
    "sierra leone",
    "singapore",
    "slovakia",
    "slovenia",
    "solomon islands",
    "somalia",
    "south africa",
    "south sudan",
    "sri lanka",
    "sudan",
    "suriname",
    "sweden",
    "switzerland",
    "syria",
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "timor-leste",
    "east timor",
    "togo",
    "tonga",
    "trinidad and tobago",
    "tunisia",
    "turkey",
    "türkiye",
    "turkiye",
    "turkmenistan",
    "tuvalu",
    "uganda",
    "ukraine",
    "united arab emirates",
    "uae",
    "united kingdom",
    "great britain",
    "britain",
    "england",
    "scotland",
    "wales",
    "northern ireland",
    "united states",
    "united states of america",
    "usa",
    "u.s.",
    "u.s.a.",
    "uruguay",
    "uzbekistan",
    "vanuatu",
    "vatican city",
    "holy see",
    "venezuela",
    "vietnam",
    "viet nam",
    "yemen",
    "zambia",
    "zimbabwe",
)

US_STATE_ABBREVIATIONS = (
    "al",
    "ak",
    "az",
    "ar",
    "ca",
    "co",
    "ct",
    "de",
    "fl",
    "ga",
    "hi",
    "id",
    "il",
    "in",
    "ia",
    "ks",
    "ky",
    "la",
    "me",
    "md",
    "ma",
    "mi",
    "mn",
    "ms",
    "mo",
    "mt",
    "ne",
    "nv",
    "nh",
    "nj",
    "nm",
    "ny",
    "nc",
    "nd",
    "oh",
    "ok",
    "or",
    "pa",
    "ri",
    "sc",
    "sd",
    "tn",
    "tx",
    "ut",
    "vt",
    "va",
    "wa",
    "wv",
    "wi",
    "wy",
    "dc",
)


def _contains_term(text: str, terms: tuple[str, ...]) -> bool:
    normalized = " ".join(text.casefold().split())
    return any(re.search(rf"(?<!\w){re.escape(term)}(?!\w)", normalized) for term in terms)


def normalized_location_scope(location: str) -> str:
    normalized = " ".join(location.casefold().split())

    # Positive evidence deliberately wins for mixed eligible scopes:
    #
    #   Spain / Portugal       -> Spain is explicitly available
    #   US / Canada / EMEA     -> EMEA explicitly includes Spain
    #
    # A specific foreign location without one of these positive signals
    # remains foreign-country-only evidence.
    if _contains_term(normalized, SPAIN_LOCATION_TERMS):
        return "spain"

    if _contains_term(normalized, BROAD_SPAIN_COMPATIBLE_TERMS):
        return "broad"

    if _contains_term(normalized, FOREIGN_COUNTRY_TERMS):
        return "foreign_country"

    state_pattern = r",\s*(?:" + "|".join(US_STATE_ABBREVIATIONS) + r")(?:\b|$)"
    if re.search(state_pattern, normalized):
        return "foreign_country"

    return "unknown"
