from __future__ import annotations

import argparse
import json
import subprocess
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AI_DIR = ROOT / ".ai"
DEFAULT_OUTPUT = AI_DIR / "GENERATED_CONTEXT.md"


def _git(*args: str) -> str:
    try:
        return subprocess.check_output(
            ["git", *args], cwd=ROOT, text=True, stderr=subprocess.STDOUT
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unavailable"


def _load_json(name: str) -> dict[str, object]:
    path = AI_DIR / name
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def _important_tree() -> list[str]:
    candidates = [
        ".ai",
        ".github/workflows",
        "backend/src/jolt",
        "backend/tests",
        "backend/migrations",
        "frontend/src",
        "docs",
        "docs/contracts",
        "tools",
    ]
    lines: list[str] = []
    for relative in candidates:
        path = ROOT / relative
        if not path.exists():
            continue
        if path.is_file():
            lines.append(relative)
            continue
        entries = sorted(
            child.name for child in path.iterdir() if not child.name.startswith("__pycache__")
        )
        preview = ", ".join(entries[:16])
        if len(entries) > 16:
            preview += f", ... (+{len(entries) - 16})"
        lines.append(f"{relative}/: {preview}")
    return lines


def _format_list(values: object) -> str:
    if not isinstance(values, list) or not values:
        return "- none recorded"
    return "\n".join(f"- {value}" for value in values)


def build_context() -> str:
    state = _load_json("PROJECT_STATE.json")
    tests = _load_json("TEST_STATUS.json")
    timestamp = datetime.now(UTC).isoformat()
    branch = _git("branch", "--show-current")
    commit = _git("rev-parse", "HEAD")
    status = _git("status", "--short") or "clean"
    recent = _git("log", "-5", "--pretty=format:%h %ad %s", "--date=short")

    readiness = state.get("readiness", {})
    current_blockers = state.get("current_blockers", [])
    next_actions = state.get("next_recommended_actions", [])
    last_evidence = state.get("last_verified_runtime_test_evidence", {})
    untested = tests.get("untested_or_not_freshly_verified_areas", [])

    lines = [
        "# Generated JOLT AI Context",
        "",
        "> Deterministic snapshot generated by `tools/build_ai_context.py`. ",
        "> Manual history/decisions remain authoritative in the other `.ai/` files; this file does not replace them.",
        "",
        f"Generated: {timestamp}",
        f"Branch: `{branch}`",
        f"Commit: `{commit}`",
        "",
        "## Git status",
        "```text",
        status,
        "```",
        "",
        "## Current milestone",
        str(state.get("current_milestone", "unknown")),
        "",
        "## Readiness",
        "```json",
        json.dumps(readiness, indent=2, ensure_ascii=False),
        "```",
        "",
        "## Current blockers",
        _format_list(current_blockers),
        "",
        "## Next recommended actions",
        _format_list(next_actions),
        "",
        "## Important repository map",
        *[f"- {line}" for line in _important_tree()],
        "",
        "## Recent commits",
        "```text",
        recent,
        "```",
        "",
        "## Last verified runtime/test evidence",
        "```json",
        json.dumps(last_evidence, indent=2, ensure_ascii=False),
        "```",
        "",
        "## Untested / not freshly verified",
        _format_list(untested),
        "",
        "## Required bootstrap reading",
        "1. `.ai/CONTEXT.md`",
        "2. `.ai/PROJECT_STATE.json`",
        "3. `.ai/KNOWN_ISSUES.md`",
        "4. `.ai/OPERABILITY.md`",
        "5. `.ai/ROADMAP.md`",
        "6. `PROJECT_MEMORY.md`",
        "7. Relevant module contract and source/tests for the active objective",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a compact deterministic JOLT AI context snapshot.")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Output path (default: .ai/GENERATED_CONTEXT.md)",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print the snapshot instead of writing a file.",
    )
    args = parser.parse_args()

    content = build_context()
    if args.stdout:
        print(content)
        return

    output = args.output if args.output.is_absolute() else ROOT / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Wrote {output.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
